[package]
name = "canvas_image_clipping"
version = "0.1.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
iced.workspace = true
iced.features = ["debug", "canvas", "image", "tokio", "advanced"]

tracing = "0.1"
tracing-subscriber = "0.3"
